### ISSUE TITLE
Deployment issue? (2016-07-04)

### ISSUE THREAD

**Issue by garrett** [gluster/planet-gluster#19] opened 2016-07-04 07:50 UTC
It looks like there's a problem with http://planet.gluster.org/ refreshing. I've checked out the repo and built it successfully, so it looks like it is a deployment issue.

@mscherer / @duck-rh: can you look at this please?

**Comment by duck-rh** [comment] 2016-07-04 08:30
Quack,

On 07/04/2016 04:50 PM, Garrett LeSage wrote:

> @mscherer https://github.com/mscherer / @duck-rh
> https://github.com/duck-rh: can you look at this please?

Sorry, Gluster is currently out of my reach. Misc should be up soon.

_o<

**Comment by mscherer** [comment] 2016-07-04 09:15
I am at a conference for the next 3 day, and from a quick verification things are running, but it take ages because at least one or more blog are kinda firewalled (for now, the build seems to spend too much time on 64.157.15.148).

**Comment by mscherer** [comment] 2016-07-04 09:27
So it build fine on the builder, and it generate the exact same website that is on planet.gluster.org. Is it supposed to be different ? 

@garrett , what is the latest post you have on your build ?

**Comment by mscherer** [comment] 2016-07-05 07:48
Ok so after checking the email, the problem is fixed now. Not sure if that was the cleanup on #20 or just a transient issue with blogspot or anything, but I do not have a way to investigate more. So closing.

**Comment by mscherer** [comment] 2016-07-08 09:13
Seems the issue is not fixed, the builder was blocked on a specific atom feed, but I couldn't reproduce the issue on my laptop. I already verified that this is not the regular rebuild code having issues. I guess wipping the ~/.gems would maybe help ?

(I will take a closed look on monday, cause I am supposed to be on PTO)

cc @nigelbabu  as a FYI on planet

**Comment by mscherer** [comment] 2016-07-08 09:14
(and the specific atom feed was the one on chriscowley.me.uk. Which work fine from my home connection.

**Comment by mscherer** [comment] 2016-07-08 09:15
And that fail because of ipv6.

**Comment by mscherer** [comment] 2021-12-21 14:57
Closing, the issue was fixed

**Closed as completed by mscherer** 2021-12-21 14:57 UTC
